name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build-release:
    runs-on: macos-15
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: "Validates GO releaser config"
        uses: goreleaser/goreleaser-action@v4
        with:
          args: check

      - name: Build Alfred workflow
        run: |
          make build

      - name: Create universal binary
        run: |
          make universal-binary

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: universal-binary
          path: workflow/alfred-zenoss-search

  release:
    needs: build-release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Download artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: universal-binary
          path: download

      - name: Copy binary into workflow
        run: |
          test -f download/alfred-zenoss-search && cp download/alfred-zenoss-search workflow/alfred-zenoss-search
          chmod +x workflow/alfred-zenoss-search
          rm -rf download

      - name: Package Alfred workflow
        run: |
          make package-alfred

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
